/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PuntodeVenta;

import DesignSoftware.BordesButton;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import DesignSoftware.FrameDesign;
import ModelDB.conexion;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.Collections;
import javax.swing.JOptionPane;

/*
 *@author Shary Yareli Chuc Ku
 *Versión: 2.0
 *Fecha última modificación: 06-12-14
 */
//  Clase que permite agregar folios en la BD.
public class AdministracionFolios extends javax.swing.JFrame {

    private conexion con = new conexion();
    private BordesButton bordesBoton;
    private int x = 0, y = 0;
    private FrameDesign img;
    public String cantidad = "0";
    String URL = "../Images/loginImages/";

    /**
     * Creates new form Emergente
     */
    public AdministracionFolios() {
        this.getContentPane().setBackground(Color.WHITE);
        initComponents();
        cargar();
        validarTab();
    }
// Método que carga unicamente el diseño a los botones.

    public void cargar() {
        img = new FrameDesign(URL + "buttonMinimize.png");
        img.addButton(btnMinimizar);
        img = new FrameDesign(URL + "buttonClose.png");
        img.addButton(btnCerrar);
    }

//    Método que activa el tab para el campo de texto.
    public void validarTab() {
        jTextField1.setFocusTraversalKeys(
                KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, Collections.EMPTY_SET);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        menuUsuarios = new javax.swing.JLabel();
        lbPermiso = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        lbPermiso1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 10));

        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 32, 32));

        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 32, 32));

        btnAñadir.setBackground(new java.awt.Color(255, 255, 255));
        btnAñadir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/articulos/accept1.png"))); // NOI18N
        btnAñadir.setText("Aceptar");
        btnAñadir.setBorder(null);
        btnAñadir.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAñadir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAñadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAñadirMouseExited(evt);
            }
        });
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 90, -1));

        menuUsuarios.setBackground(new java.awt.Color(116, 16, 30));
        menuUsuarios.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        menuUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuUsuarios.setText("FOLIOS");
        menuUsuarios.setDoubleBuffered(true);
        menuUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuUsuarios.setOpaque(true);
        menuUsuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuUsuariosMouseDragged(evt);
            }
        });
        menuUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuUsuariosMousePressed(evt);
            }
        });
        getContentPane().add(menuUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));

        lbPermiso.setBackground(new java.awt.Color(255, 255, 255));
        lbPermiso.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lbPermiso.setText("Folio");
        lbPermiso.setOpaque(true);
        getContentPane().add(lbPermiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 20));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1-25", "1-50", "1-100", "1-300", "1-500", "1-1000" }));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 80, 30));

        lbPermiso1.setBackground(new java.awt.Color(255, 255, 255));
        lbPermiso1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lbPermiso1.setText("No. Folios Digitales");
        lbPermiso1.setOpaque(true);
        getContentPane().add(lbPermiso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 100, 20));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    Toma las pocisiones del frame
    private void menuUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuariosMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_menuUsuariosMousePressed

//    Hace que tenga movimiento el jframe
    private void menuUsuariosMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuariosMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_menuUsuariosMouseDragged

    private void btnAñadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAñadirMouseEntered
        try {
            bordesBoton = new BordesButton(btnAñadir);
            bordesBoton.encender();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAñadirMouseEntered

    private void btnAñadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAñadirMouseExited

        bordesBoton = new BordesButton(btnAñadir);
        bordesBoton.apagar();
    }//GEN-LAST:event_btnAñadirMouseExited

//Evento que ingresa a la BD los folios
    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        int folios = 0;
        try {
            if (jComboBox1.getSelectedIndex() == 0) {
                folios = 25;
            } else if (jComboBox1.getSelectedIndex() == 1) {
                folios = 50;
            } else if (jComboBox1.getSelectedIndex() == 2) {
                folios = 100;
            } else if (jComboBox1.getSelectedIndex() == 3) {
                folios = 300;
            } else if (jComboBox1.getSelectedIndex() == 4) {
                folios = 500;
            } else if (jComboBox1.getSelectedIndex() == 5) {
                folios = 1000;
            }
            if (jTextField1.getText().length() < 4 || jTextField1.getText().length() > 4) {
                JOptionPane.showMessageDialog(null, "FOLIO: 4 CARACTERES\nUNICAMENTE");
                jTextField1.requestFocus(true);
            } else {
                con.agregar("folios", "folio,cantidad,estado", jTextField1.getText() + "," + folios + ",1");
                this.hide();
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                btnAñadir.requestFocus(true);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

//    Evento que condiciona que el folio debe llevar 4 letras.
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        String mayuscula = "";
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            try {
                mayuscula = jTextField1.getText().trim().toUpperCase();
                if (mayuscula.length() > 4) {
                    JOptionPane.showMessageDialog(null, "FOLIO DE 4 CARACTERES\nUNICAMENTE.");
                    jTextField1.requestFocus();
                } else {
                    jTextField1.setText(mayuscula);
                    jComboBox1.requestFocus();
                }

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        try {
            img = new FrameDesign(URL + "buttonMinimize1.png");
            img.addButton(btnMinimizar);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        try {
            img = new FrameDesign(URL + "buttonMinimize.png");
            img.addButton(btnMinimizar);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        try {
            img = new FrameDesign(URL + "buttonClose1.png");
            img.addButton(btnCerrar);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        try {
            img = new FrameDesign(URL + "buttonClose.png");
            img.addButton(btnCerrar);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCerrarMouseExited

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.hide();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbPermiso;
    private javax.swing.JLabel lbPermiso1;
    private javax.swing.JLabel menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
