/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PuntodeVenta;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import DesignSoftware.FrameDesign;
import Notificaciones.BdTabla;
import java.awt.Font;
import javax.swing.table.JTableHeader;
import ModelDB.conexion;

/*
 *@author Shary Yareli Chuc Ku
 *Versión: 2.0
 *Fecha última modificación: 06-12-14
 */
//Su funcion principal es unicamente cargar los datos requeridos para las notificaciones de eventos importantes en el sistema.
public class EmergenteNotificaciones extends javax.swing.JFrame {

    private int x = 0, y = 0;
    private FrameDesign img;
    private JTableHeader Header;
    private conexion con = new conexion();
    String URL = "../Images/loginImages/";

    /**
     * Creates new form Emergente
     */
//    Constructor: Llama a los métodos cargar() & folio().
    public EmergenteNotificaciones() {
        this.getContentPane().setBackground(Color.WHITE);
        initComponents();
        cargar();
        folio();
    }

//    Carga el diseño de los botones y la tabla.
    public void cargar() {
        try {
            img = new FrameDesign(URL + "buttonMinimize.png");
            img.addButton(btnMinimizar);
            img = new FrameDesign(URL + "buttonClose.png");
            img.addButton(btnCerrar);

            Header = jtavisos.getTableHeader();
            Header.setForeground(new Color(116, 16, 30));
            Header.setFont(new Font("Times New Roman", Font.BOLD, 10));
            Notificaciones.BdTabla not = new BdTabla(jtavisos);
        } catch (Exception e) {
        }
    }

//    Verifica las notificaciones que irán en el campo de texto, de acuerdo si cumple a las condiciones especificadas.
    public void folio() {
        try {
            int estado = 0;
            String folio = "";
            String estadoCadena = "";
            con.busquedaID("folios");
            String numeroPrueba = String.valueOf(con.registro_busqueda);
            if ("null".equals(numeroPrueba)) {
                txtAvisoFolio.setText("Urgente!!!\nIngrese folios.");
            } else {
                con.busqueda("folios", "estado", "folio", "1");
                folio = con.registro_busqueda;
                if ("".equals(folio)) {
                    txtAvisoFolio.setText("Urgente!!!\nIngrese folios.");
                } else {
                    txtAvisoFolio.setText("Aun tiene folios disponibles.");
                }
            }
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMinimizar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        menuUsuarios = new javax.swing.JLabel();
        lbPermiso1 = new javax.swing.JLabel();
        txtAvisoFolio = new javax.swing.JTextField();
        lbPermiso = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        scrolArticulos = new javax.swing.JScrollPane();
        jtavisos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 32, 32));

        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 32, 32));

        menuUsuarios.setBackground(new java.awt.Color(116, 16, 30));
        menuUsuarios.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        menuUsuarios.setText("    NOTIFICACIONES IMPORTANTES");
        menuUsuarios.setDoubleBuffered(true);
        menuUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuUsuarios.setOpaque(true);
        menuUsuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuUsuariosMouseDragged(evt);
            }
        });
        menuUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuUsuariosMousePressed(evt);
            }
        });
        getContentPane().add(menuUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 50));

        lbPermiso1.setBackground(new java.awt.Color(255, 255, 255));
        lbPermiso1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lbPermiso1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPermiso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginImages/producto.png"))); // NOI18N
        lbPermiso1.setOpaque(true);
        getContentPane().add(lbPermiso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, 40));

        txtAvisoFolio.setEditable(false);
        txtAvisoFolio.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        txtAvisoFolio.setPreferredSize(new java.awt.Dimension(10, 25));
        txtAvisoFolio.setSelectionColor(new java.awt.Color(91, 137, 193));
        txtAvisoFolio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAvisoFolioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAvisoFolioFocusLost(evt);
            }
        });
        getContentPane().add(txtAvisoFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 80));

        lbPermiso.setBackground(new java.awt.Color(255, 255, 255));
        lbPermiso.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lbPermiso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPermiso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginImages/conf1.png"))); // NOI18N
        lbPermiso.setText(" Folio");
        lbPermiso.setOpaque(true);
        getContentPane().add(lbPermiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 340, 10));

        scrolArticulos.setBackground(new java.awt.Color(255, 255, 255));
        scrolArticulos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(116, 16, 30)));
        scrolArticulos.setForeground(new java.awt.Color(255, 255, 255));
        scrolArticulos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtavisos.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jtavisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "CÓDIGO "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtavisos.setGridColor(new java.awt.Color(116, 16, 30));
        jtavisos.setOpaque(false);
        jtavisos.setSelectionBackground(new java.awt.Color(91, 137, 193));
        scrolArticulos.setViewportView(jtavisos);

        getContentPane().add(scrolArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 170, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuariosMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_menuUsuariosMousePressed

    private void menuUsuariosMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuariosMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_menuUsuariosMouseDragged

    private void txtAvisoFolioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAvisoFolioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvisoFolioFocusGained

    private void txtAvisoFolioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAvisoFolioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvisoFolioFocusLost

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        try {
            img = new FrameDesign(URL + "buttonMinimize1.png");
            img.addButton(btnMinimizar);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        try {
            img = new FrameDesign(URL + "buttonMinimize.png");
            img.addButton(btnMinimizar);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        try {
            img = new FrameDesign(URL + "buttonClose1.png");
            img.addButton(btnCerrar);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        try {
            img = new FrameDesign(URL + "buttonClose.png");
            img.addButton(btnCerrar);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCerrarMouseExited

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.hide();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTable jtavisos;
    private javax.swing.JLabel lbPermiso;
    private javax.swing.JLabel lbPermiso1;
    private javax.swing.JLabel menuUsuarios;
    private javax.swing.JScrollPane scrolArticulos;
    private javax.swing.JTextField txtAvisoFolio;
    // End of variables declaration//GEN-END:variables
}
